apiVersion: v1
kind: Secret
metadata:
  name: api-secret
  namespace: ers-backend
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "Server=sqlserver.ers-db.svc.cluster.local,1433;Database=ElectronicsRepairShop;User Id=sa;Password=P@ssw0rd2026SecureERS!;TrustServerCertificate=True;"
  
  JWT_SECRET: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9eyJpc3MiOiJFUlMiLCJleHAiOjE3NzExOTUyMDB9kK5xZ"
  SENDGRID_API_KEY: "SG.7nR2qK9mL0pQwXvYzA1bCdEfGhIjKlMnOpQrStUvWxYzAbCdEfGhIjK"
