apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver
  namespace: ers-db
  labels:
    app: sqlserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlserver
  template:
    metadata:
      labels:
        app: sqlserver
    spec:
      containers:
      - name: sqlserver
        image: mcr.microsoft.com/mssql/server:2022-latest
        imagePullPolicy: Never
        ports:
        - containerPort: 1433
