apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: ers-frontend
  labels:
    app: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: ersfront:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 5173
